version: '3.7'

services: 
  eog:
    container_name: eog
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    expose: ['3000']
    ports:
      - '80:3000'
    command: ['yarn', 'start']
    volumes: 
      - './src:/app/src'
    stdin_open: true